name: Testing

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Get dependencies
      run: go mod download

    - name: Start gRPC server
      run: go run ./cmd/main.go --config=./config/local.yaml &


  test:
    needs: run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./tests/...